version: '2'

services:
  talker:
    image: l2base:latest
    command: ros2 run demo_nodes_cpp talker
  listener:
    image: l2base:latest
    command: /bin/bash -c "ros2 topic echo /chatter"
    environment: 
      PYTHONUNBUFFERED: 1
    depends_on:
      - talker
