version: '3.5'

services:
  main:
    image: l2example:latest
    pid: "host" # TODO(https://github.com/ros2/rmw_fastrtps/issues/349)
    networks:
      - l2

networks:
  l2:
    driver: bridge
    name: l2
