version: '2.3'

services:
  talker:
    image: l2base:latest
    command: ros2 run demo_nodes_cpp talker
  listener:
    image: l2base:latest
    command: /bin/bash -c "ros2 topic echo /chatter"
    environment: 
      PYTHONUNBUFFERED: 1
    depends_on:
      - talker
  sdf:
    image: l2base:latest
    volumes:
      - ./sdf:/sdf
    command: bash -c "PYTHONUNBUFFERED=1 /sdf/publish_sdf.sh control_zone /sdf/control_zone.sdf"
    network_mode: host
  gz:
    image: l2sim:latest
    command: bash -c "source /opt/ros/dashing/setup.bash && source /usr/share/gazebo/setup.sh && gzserver --verbose /opt/ros/dashing/share/gazebo_plugins/worlds/gazebo_ros_diff_drive_demo.world"
    network_mode: host
