version: '3.4'

services:
  gzweb:
    image: docker.io/osrf/gazebo:gzweb8
    command: npm start
    network_mode: bridge
    environment:
      - "GAZEBO_MASTER_URI=http://172.104.130.198:11345"
    ports:
      - "8080:8080"
      - "80:80"
    links:
      - gz
  sdf_control_zone:
    image: l2sim:latest
    volumes:
      - /home/smartin015/l2_makerspace/infra/ros/sim/sdf:/sdf
    command: bash -i -c "PYTHONUNBUFFERED=1 /sdf/spawn_object3d.sh control_zone /sdf/control_zone.sdf 1.0 0.5 0.5 0.5"
    network_mode: bridge
  sdf_testbox:
    image: l2sim:latest
    volumes:
      - /home/smartin015/l2_makerspace/infra/ros/sim/sdf:/sdf
    command: bash -i -c "PYTHONUNBUFFERED=1 /sdf/spawn_object3d.sh testbox /sdf/testbox.sdf 1.0 0.5 0.5 0.5"
    network_mode: bridge
  gz:
    image: l2sim:latest
    command: bash -c "source /opt/ros/dashing/setup.bash && source /usr/share/gazebo/setup.sh && gzserver -s libgazebo_ros_factory.so -s libgazebo_ros_state.so -s libgazebo_ros_init.so"
    network_mode: bridge
    ports:
      - "11345:11345"
