version: '3.5'

services:
  sim:
    image: l2sim
    pid: "host" # TODO(https://github.com/ros2/rmw_fastrtps/issues/349)
    networks:
      - l2
    volumes:
      - "webots:/tmp"
      - "./tmp:/cfg"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=$DISPLAY"
      - "PYTHONUNBUFFERED=1"
    command: /ros_entrypoint.sh ros2 run l2_sim node --ros-args -p report_path:=/test -p object_config:=single_motor -r __ns:=/l2
  
  example_controller:
    image: l2sim
    volumes:
      - "webots:/tmp"
    networks:
      - l2
    environment:
      - "WEBOTS_HOME=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/"
      - "LD_LIBRARY_PATH=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/lib/controller"
      - "WEBOTS_ROBOT_NAME=single_motor"
    command: /ros_entrypoint.sh ros2 run l2_sim example_controller --ros-args -p synchronization:=False -r __ns:=/l2
    restart: always
    depends_on:
      - sim

  pendant_controller:
    image: l2sim
    volumes:
      - "webots:/tmp"
    networks:
      - l2
    environment:
      - "WEBOTS_HOME=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/"
      - "LD_LIBRARY_PATH=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/lib/controller"
      - "WEBOTS_ROBOT_NAME=pendant"
    command: /ros_entrypoint.sh ros2 run l2_sim pendant_controller --ros-args -p synchronization:=False -r __ns:=/l2

  range_controller:
    image: l2sim
    ipc: host
    pid: host
    volumes:
      - "webots:/tmp"
    networks:
      - l2
    environment:
      - "WEBOTS_HOME=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/"
      - "LD_LIBRARY_PATH=/webots_ros2/install/webots_ros2_desktop/share/webots_ros2_desktop/webots/lib/controller"
      - "PYTHONFAULTHANDLER=1"
      - "PYTHONUNBUFFERED=1"
      - "WEBOTS_ROBOT_NAME=range"
    command: /ros_entrypoint.sh ros2 run l2_sim rangefinder_controller --ros-args -p synchronization:=False -r __ns:=/l2

networks:
  l2:
    driver: bridge
    name: l2

volumes:
  webots:
