version: '3.5'

services:
  main:
    image: l2supervisor:latest
    pid: "host" # TODO(https://github.com/ros2/rmw_fastrtps/issues/349)
    networks:
      - l2
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "./config.yaml:/config.yaml"
  example:
    image: l2base:latest
    pid: host
    networks:
      - l2
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - ./test:/test
    command: /test/test_sequence.sh

networks:
  l2:
    driver: bridge
    name: l2
