version: '3.5'
services:
  vr_syncer:
    image: l2vr:latest
    pid: "host" # TODO(https://github.com/ros2/rmw_fastrtps/issues/349)
    networks:
      - l2
    environment:
      - PYTHONUNBUFFERED=1
    command: ros2 run l2_vr node
    #__log_level:=debug

networks:
  l2:
    driver: bridge
    name: l2
